apiVersion: v1
kind: Service
metadata:
  name: mq-rcvr
  namespace: supreme-doodle
spec: 
  selector:
    application: helloworld
    service: mq-rcvr  
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
